import {Inter} from '@next/font/google'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, {useEffect} from "react";
import {postArray, postFetchData} from "../api/post.api";
import {useQuery} from "@tanstack/react-query";

const inter = Inter({subsets: ['latin']})


export default function Home() {
    // const [posts, setPosts] = useState<postArray>([])

    // data fetch with useQuery hook
    const {data: posts, isLoading, isError, error} = useQuery<postArray, Error>(['posts'], () => postFetchData)
    useEffect(() => {
        console.log(posts)
        console.log(isLoading)
        console.log(isError)
        console.log(error)
    })


    return (
        <>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>

                {posts?.map(post => {
                    return (
                        <div key={post.id}>
                            <h1>{post.title}</h1>
                            <p>{post.body}</p>
                        </div>
                    )
                })}

            </main>
        </>
    )
}
