import { Inter, } from '@next/font/google'
import Head from 'next/head'
import React from "react";
import Filter from '../../components/Organisms/Filter/filter';
import Base from '../../components/templates/Base/Base';



const inter = Inter({ subsets: ['latin'] })


export default function FilTer() {
    return (
        <>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Base inner={[<Filter key={1} />]} />
        </>
    )
}
